site_name: YYHhao的个人博客
nav:
  - 主页: index.md
  - python:
    - numpy模块: 
      - 基本操作: numpy模块/mynumpy.md
      - 随机生成: numpy模块/随机生成.md
      - nonzero函数: numpy模块/nonzero函数.md
    - pandas模块: 
      - 基本操作: pandas模块/mypandas.md 
      - map()和apply(): pandas模块/map_apply.md
      - DataFrame合并: pandas模块/合并方法.md
      - Grouping、Sorting和rename : pandas模块/mygroupby.md
    - sklearn模块:
      - 交叉验证生成器: sklearn模块/交叉验证.md
      - 文本数据处理: sklearn模块/文本数据处理.md
    - 算法学习: 
      - 欧几里得算法、中国剩余定理: alglearning/mylearning1.md
      - 模拟退火算法: alglearning/SA.md
    - 爬虫学习: 
      - 多线程、异步爬虫: pachong/mypachong1.md
      - 进、线、协程的概念: pachong/mypachong2.md
    - 机器学习:
      - 损失函数: ml/lossfun.md
      - EM算法: ml/EM算法.md
      - 高斯混合模型: ml/高斯混合模型.md
      - 降维算法: 
        - 前言: ml/降维算法/jiangwei.md
        - PCA: ml/降维算法/mypca.md
        - ICA: ml/降维算法/myica.md
        - LDA: ml/降维算法/mylda.md
      - 聚类算法: 
        - 前言: ml/聚类算法/clusteralg.md
        - 层次聚类: ml/聚类算法/层次聚类.md
        - DBSCAN: ml/聚类算法/Dbscan.md
        - OPTICS: ml/聚类算法/OPTICS.md
        - 高斯混合聚类: ml/聚类算法/高斯混合聚类.md
      - 分类算法: ml/分类算法/classifyalg.md
      - 回归算法: ml/回归算法/regressionalg.md
    - 深度学习:
      - 神经网络权重初始化0问题: dl/初始化.md
    - 数据处理及可视化: 
      - matplotlib中文编码: datapv/mydatapv.md
    - HTML和XML: 
      - 简介与解析: html_xml/简介与解析.md
  - CV: 
    - 读取图片: cvlearning/读取图片.md
    - opencv中文路径问题: cvlearning/中文报错问题.md
  - 数学建模: 
    - 前言: 数学建模/前言.md
    - 优化模型:
      - 多目标规划: 数学建模/优化模型/多目标规划.md
    - 评价模型:
      - 层次分析法: 数学建模/评价模型/层次分析.md
    - 预测模型:
      - 灰色预测: 数学建模/预测模型/灰色预测.md
    - 统计模型:
      - 聚类分析: 数学建模/统计模型/聚类分析.md
  - NLP:
    - 前言: NLP/前言.md
  - 笔记:
    - git学习: bj/mygit.md
    - 编码(encode)与解码(decode): bj/编码与解码.md
    - pip的使用: bj/pip使用.md
    - Anaconda虚拟环境: bj/虚拟环境.md
      
theme:
  name: 'material'
  logo: 'img/火箭.svg'
  favicon: 'img/火箭.svg'
  palette:
      primary: 'cyan'
      accent: 'deep orange'

#自动调节白天夜间模式
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


 